package fake

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/big"
	"strings"
	"time"

	"github.com/promptrails/promptrails-local/internal/model"
	"github.com/segmentio/ksuid"
)

// GenerateExecutionOutput creates a simulated LLM response for an agent execution.
// Returns a map suitable for JSON marshalling as the execution output.
func GenerateExecutionOutput(agentName string, input map[string]any) map[string]any {
	inputKeys := make([]string, 0, len(input))
	for k := range input {
		inputKeys = append(inputKeys, k)
	}

	content := fmt.Sprintf(
		"[Simulated response for agent %q] Input keys: %s. "+
			"This is a fake response generated by the PromptRails local emulator.",
		agentName, strings.Join(inputKeys, ", "),
	)

	return map[string]any{
		"content": content,
		"type":    "text",
	}
}

// GeneratePromptRunResponse creates a simulated response for a prompt run.
func GeneratePromptRunResponse(promptName string) model.RunPromptResponse {
	content := fmt.Sprintf(
		"[Simulated LLM response for prompt %q] "+
			"This is a fake response from the PromptRails local emulator.",
		promptName,
	)

	promptTokens := randomInt(50, 300)
	completionTokens := randomInt(30, 200)

	return model.RunPromptResponse{
		Content: content,
		TokenUsage: map[string]int{
			"prompt_tokens":     promptTokens,
			"completion_tokens": completionTokens,
			"total_tokens":      promptTokens + completionTokens,
		},
		Cost:       float64(promptTokens)*0.000003 + float64(completionTokens)*0.000015,
		DurationMS: int64(randomInt(150, 1500)),
		Model:      "gpt-4o",
		TraceID:    GenerateTraceID(),
	}
}

// GenerateChatResponse creates a simulated chat assistant reply.
func GenerateChatResponse(agentID string, userContent string) string {
	return fmt.Sprintf(
		"[Simulated assistant reply for agent %s] You said: %q. "+
			"This is a fake response from the PromptRails local emulator.",
		agentID, truncate(userContent, 120),
	)
}

// GenerateTraceID returns a random 16-byte hex string suitable for use as a trace ID.
func GenerateTraceID() string {
	b := make([]byte, 16)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// GenerateSpanID returns a random 8-byte hex string suitable for use as a span ID.
func GenerateSpanID() string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// CreateExecutionTrace creates a root span and a child LLM span for an execution,
// returning them as a slice of Trace models.
func CreateExecutionTrace(exec model.Execution, agentName string) []model.Trace {
	now := time.Now()
	traceID := exec.TraceID
	rootSpanID := GenerateSpanID()
	childSpanID := GenerateSpanID()

	durationMS := 0
	if exec.DurationMS != nil {
		durationMS = int(*exec.DurationMS)
	}
	childDuration := durationMS
	if childDuration > 50 {
		childDuration -= 50
	}

	endedAt := now.Add(time.Duration(durationMS) * time.Millisecond)
	childEndedAt := now.Add(time.Duration(childDuration) * time.Millisecond)

	rootTrace := model.Trace{
		ID:          ksuid.New().String(),
		WorkspaceID: exec.WorkspaceID,
		TraceID:     traceID,
		SpanID:      rootSpanID,
		Name:        fmt.Sprintf("agent.execute(%s)", agentName),
		Kind:        "agent",
		Status:      "ok",
		Level:       "DEFAULT",
		Input:       exec.Input,
		Output:      exec.Output,
		Attributes:  json.RawMessage(`{}`),
		Tags:        json.RawMessage(`["agent","execution"]`),
		TokenUsage:  exec.TokenUsage,
		Cost:        &exec.Cost,
		DurationMS:  &durationMS,
		AgentID:     exec.AgentID,
		ExecutionID: &exec.ID,
		SessionID:   exec.SessionID,
		StartedAt:   now,
		EndedAt:     &endedAt,
		CreatedAt:   now,
	}

	childTrace := model.Trace{
		ID:           ksuid.New().String(),
		WorkspaceID:  exec.WorkspaceID,
		TraceID:      traceID,
		SpanID:       childSpanID,
		ParentSpanID: rootSpanID,
		Name:         "llm.generate",
		Kind:         "llm",
		Status:       "ok",
		Level:        "DEFAULT",
		Input:        exec.Input,
		Output:       exec.Output,
		Attributes:   json.RawMessage(`{"model":"gpt-4o"}`),
		Tags:         json.RawMessage(`["llm"]`),
		TokenUsage:   exec.TokenUsage,
		Cost:         &exec.Cost,
		DurationMS:   &childDuration,
		ModelName:    "gpt-4o",
		AgentID:      exec.AgentID,
		ExecutionID:  &exec.ID,
		SessionID:    exec.SessionID,
		StartedAt:    now,
		EndedAt:      &childEndedAt,
		CreatedAt:    now,
	}

	return []model.Trace{rootTrace, childTrace}
}

func randomInt(min, max int) int {
	n, _ := rand.Int(rand.Reader, big.NewInt(int64(max-min+1)))
	return int(n.Int64()) + min
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "..."
}
